### ISSUE TITLE
font variable animeren met css

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#102]

**Comment by yujing-student** [comment]
![Image](https://github.com/user-attachments/assets/76f1beb5-b67e-4e1c-95f7-29bdf90f8fb1)


https://wakamaifondue.com/


hier kan je het font aanpassen en animeren met css

**Comment by lisagjh** [comment]
Verschrikkelijk vervelende animatie maar stiekem toch wel leuk?

https://github.com/user-attachments/assets/21811b65-bd50-4871-b264-14c8abcf9757

```css
h1 {
    animation: welcome 1.5s ease-in-out 12 alternate;
  }

  h1:hover {
    animation-play-state: paused;
  }

  @keyframes welcome {
    0% {
      font-weight: 100;
      letter-spacing: .5rem;
    }
    30% {
      font-weight: 900;
      letter-spacing: -.5rem;
    }
    60% {
      font-weight: 100;
      letter-spacing: -.5rem;
    }
    100% {
      font-weight: 900;
      letter-spacing: .5rem;
    }
  }
```
