### ISSUE TITLE
# bouwen spin animatie

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#130]
maken spin animatie

zie hier de codepen

https://codepen.io/argyleink/pen/wvOKbyL/2d672362df9ac37cf6920b5b6bc3a243

**Comment by Yu-Jing-van-Gerwen** [comment]
<h1>code</h1>

mocht de video het niet doen dan kan je refresehn op de pagina en dan zou di het moeten doen

https://github.com/user-attachments/assets/eec036ed-001b-4728-bef2-92c69039b12f



# html code

````Svelte
{#each data.members as member}

        <article class="card">
            <picture>
                <source srcset="https://fdnd-agency.directus.app/assets/{member.photo}?format=avif" type="image/avif">
                <source srcset="https://fdnd-agency.directus.app/assets/{member.photo}?format=webp" type="image/webp">
                <img src="https://fdnd-agency.directus.app/assets/{member.photo}" loading="lazy" alt="">
            </picture>

            <ul class="card-label-filters">
                <li class="label-filters">
                    service design
                </li>
                <li class="label-filters">label</li>
            </ul>

            <h2>{member.title}</h2>
            <p>{member.address}</p>

            <ul class="card-label">
                <li>{parseInt(member.colleagues)}  werknemers</li>
                <li class="card-hiring">hiring</li>

            </ul>

            <Link href="/" clazz="detail-link"><span slot="link-text">Details</span>
                <svg width="16" height="16" slot="svg-icon-right" viewBox="0 0 24 24" fill="none">
                    <path d="M6 12H18M18 12L13 7M18 12L13 17" stroke-width="2" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </Link>

        </article>
    {/each}
````

# bouwen spin animatie

maken spin animatie 

````css

   .card:nth-child(odd)
        {

            animation: spin both ;
            /*animation: slideLeftAnimation both ;*/
            animation-timeline: view();
        }


  @keyframes spin {
            to {
                transform: rotateY(1turn);
            }
        }

        @media (prefers-reduced-motion: no-preference) {
            .card {
                animation: spin linear;
                animation-timeline: view();
                animation-range: contain;
            }
        }
````


_Originally posted by @yujing-student in https://github.com/fdnd-agency/voorhoede/issues/120#issuecomment-2517275025_



# bouwen cards slide up

````css 
  .card:nth-child(even)
        {

            animation: slide-in-up both ;
            animation-timeline: view();
        }
@keyframes slide-in-up {
        0% {
            transform: translateY(50em);
            background: rgb(98,194,6);
            background: linear-gradient(76deg, rgba(98,194,6,1) 0%, rgba(230,39,39,1) 12%, rgba(170,255,253,1) 47%, rgba(117,114,140,1) 100%);
        }
        25% {
            transform: translateY(25em);
            background: linear-gradient(225deg, rgba(98,194,6,1) 0%, rgba(230,39,39,1) 12%, rgba(170,255,253,1) 47%, rgba(117,114,140,1) 100%);
        }
        50% {
            transform: translateY(0em);
            background: rgb(98,194,6);
            background: radial-gradient(circle, rgba(98,194,6,1) 0%, rgba(230,39,39,1) 12%, rgba(170,255,253,1) 47%, rgba(117,114,140,1) 100%);
        }
    }
    
````
