### ISSUE TITLE
slide left animatie

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#134]
link naar code pen: https://codepen.io/66kesara99/pen/abeEgrr

**Comment by yujing-student** [comment]
https://github.com/user-attachments/assets/d5cf5d2b-7306-4723-8ac2-118c9d91b58c


````svelte
{#each data.members as member}

        <article class="card">
            <picture>
                <source srcset="https://fdnd-agency.directus.app/assets/{member.photo}?format=avif" type="image/avif">
                <source srcset="https://fdnd-agency.directus.app/assets/{member.photo}?format=webp" type="image/webp">
                <img src="https://fdnd-agency.directus.app/assets/{member.photo}" loading="lazy" alt="">
            </picture>

            <ul class="card-label-filters">
                <li class="label-filters">
                    service design
                </li>
                <li class="label-filters">label</li>
            </ul>

            <h2>{member.title}</h2>
            <p>{member.address}</p>

            <ul class="card-label">
                <li>{parseInt(member.colleagues)}  werknemers</li>
                <li class="card-hiring">hiring</li>

            </ul>

            <Link href="/" clazz="detail-link"><span slot="link-text">Details</span>
                <svg width="16" height="16" slot="svg-icon-right" viewBox="0 0 24 24" fill="none">
                    <path d="M6 12H18M18 12L13 7M18 12L13 17" stroke-width="2" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </Link>

        </article>
    {/each}


````


css code 

````css

.card
        {

            animation: slideLeftAnimation both ,gradient-animation 2s infinite;
            animation-timeline: view();
        }


 @keyframes slideLeftAnimation {
        0% {
            transform: translateX(-50em);

        }
        25% {
            transform: translateX(-25em);
        }

        50%{
            background: rgb(2,0,36);
            background: linear-gradient(139deg, rgba(2,0,36,1) 0%, rgb(212, 212, 248) 47%, rgba(0,212,255,1) 100%);
            transform: translateX(0em);
        }
    }
````
