### ISSUE TITLE
lege ruimte tussen eerste en 2de card oplossen

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#135]
![image](https://github.com/user-attachments/assets/18f0f45b-3c57-409b-b236-2c0f4a3791f2)

**Comment by yujing-student** [comment]
https://github.com/user-attachments/assets/062e2af2-217c-4d13-9981-f24cd2784b47

````css

  .card
        {

            animation: slide-in-up both ,gradient-animation 2s infinite;
            animation-timeline: view();
        }

 @keyframes slide-in-up {
     

        0% {
            transform: translateY(10em);
            background: rgb(98,194,6);
            background: linear-gradient(50deg, rgba(2,0,36,1) 0%, rgb(226, 244, 198) 25%, rgba(0,212,255,1) 100%);
        }
        25%{
            transform: translateY(5em);
            background: rgb(98,194,6);
            background: linear-gradient(139deg, rgba(2,0,36,1) 0%, rgb(212, 212, 248) 47%, rgba(0,212,255,1) 100%);
        }
        50%{
                transform: translateY(0em);
                background: rgb(98,194,6);
                background: linear-gradient(20deg, rgb(255, 253, 253) 0%, rgb(255, 213, 213) 47%, rgba(0,212,255,1) 100%);
        }
   
    }

````
