### ISSUE TITLE
Spike 1 ontwerpen 

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#140]
een snelle wireflow

![IMG_1210](https://github.com/user-attachments/assets/640f7dea-df39-49f4-852a-fcb72372d5df)

de wireflow uitgewerkt figma file https://www.figma.com/design/0FjBuy61FzkTk199dv7LFG/sprint-17?node-id=23-2622&m=dev&t=PTyB4dGT59bhcWai-1

![image](https://github.com/user-attachments/assets/6b08d7b1-99e6-4932-8932-adfe9155cb20)

**Comment by yujing-student** [comment]
<h1>breakdownschets</h1>

![image](https://github.com/user-attachments/assets/1aa2d95a-e55f-4da3-aae9-d380b9b34bab)


![image](https://github.com/user-attachments/assets/026bdfea-d6e6-45fc-9cf9-bb3d73ca075a)

![image](https://github.com/user-attachments/assets/0124e759-79b5-43b2-a544-69da4b8cb1ce)

**Comment by yujing-student** [comment]
code uitgewerkt

````svelte 
 {#each data.members as member}

        <article class="card">
            <picture>
                <source srcset="https://fdnd-agency.directus.app/assets/{member.photo}?format=avif" type="image/avif">
                <source srcset="https://fdnd-agency.directus.app/assets/{member.photo}?format=webp" type="image/webp">
                <img src="https://fdnd-agency.directus.app/assets/{member.photo}" loading="lazy" alt="{member.title}">
            </picture>

            <ul class="card-label-filters">
                <li class="label-filters">
                    service design
                </li>
                <li class="label-filters">label</li>
            </ul>

            <h2 aria-label="{member.title}">{member.title}</h2>
            <p>{member.address}</p>

            <ul class="card-label">
                <li>{parseInt(member.colleagues)}  werknemers</li>
                <li class="card-hiring">hiring</li>

            </ul>

            <Link href="/" clazz="detail-link"><span slot="link-text">Details</span>
                <svg width="16" height="16" slot="svg-icon-right" viewBox="0 0 24 24" fill="none">
                    <path d="M6 12H18M18 12L13 7M18 12L13 17" stroke-width="2" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </Link>

        </article>
    {/each}
````

````css

body{
  background: rgb(129, 228, 168);
  background: linear-gradient(83deg, rgb(240 184 184) 0%, rgb(194, 250, 243) 47%, rgb(255 174 249) 100%);
}


  @keyframes slide-in-up {


        0% {

            transform: translateY(10em);
    background-color: white;
        }
        25% {
            transform: translateY(5em);
    background-color: white;
        }
        50% {
        background-color: white;
        }

    }


    @keyframes gradient-animation {
        0% {
            background-position: 0% 50%;   background-color: white;
        }
        100% {
            background-position: 100% 50%;
        }
    }
````

met prefers reduced motion word aangegeven dat mensen die geen voorkeur hebben deze animatie te zien krijgen en mensen die wel voorkeuren hebben krijgen de animatie niet te zien
````css
  @media (prefers-reduced-motion: no-preference) {
        img {
            animation: reveal 1s linear both;
            /* Rember to declare the timeline after the shorthand */
            animation-timeline: view();
        }
    }


@media (prefers-reduced-motion: no-preference) {
        .card {
            animation: slide-in-up both, white-background-cards 2s infinite;
            animation-timeline: view();
        }
    }
````
