### ISSUE TITLE
animatie maken waarin de cards draaien en een blur hebben en een knop om de card recht te zetten

### ISSUE THREAD

**Issue by yujing-student** [fdnd-agency/voorhoede#150]

**Comment by yujing-student** [comment]
dit is de code van de view transitons`



```css
    @media (prefers-reduced-motion: no-preference) {
        .card {
            animation: Rotate both, white-background-cards 2s infinite;
            animation-timeline: view();
        }
    }
    :global(.card.active) {
        background: linear-gradient(300deg, rgb(128, 216, 250) 0%, rgb(235, 235, 255) 47%, rgba(0,212,255,1) 100%);
        rotate: 348deg;

    }

```

````javascript
 onMount(() => {
        if (document.startViewTransition) {
            const buttons = document.querySelectorAll('.button');
            for (let i = 0; i < buttons.length; i++) {
                buttons[i].addEventListener('click', () => {
                    const clickedCard = buttons[i].closest('.card');
                    document.startViewTransition(() =>
                        clickedCard.classList.toggle('active')
                    )
                });
            }

            // https://codepen.io/user46frontend/pen/PwYzyZG eigne voorbeeld
        }

````



````css
 @keyframes Rotate {


        0% {
            /*background-color: red;*/
            transform: translateY(10em);
            filter: blur(25px);
            transition: filter 0.3s ease-in-out;
            rotate: 405deg;
        }
        25% {
            transform: translateY(5em);
            filter: blur(15px);
            transition: filter 0.3s ease-in-out;
        }
        50% {
            filter: blur(0px);
            transition: filter 0.3s ease-in-out;
        }

        100%{
            filter: blur(10px);
            transition: filter 0.3s ease-in-out;
        }

    }

````
