### ISSUE TITLE
Add skiplink to nav to allow skipping to main content

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/voorhoede#80]
[skiplink](https://www.a11yproject.com/posts/skip-nav-links/)

**Comment by lisagjh** [comment]
Ik ben begonnen met kijken hoe ik de skip link kan toevoegen, zodat gebruikers die bijvoorbeeld een screen reader gebruiken niet elke keer weer door het hele menu heen hoeven. 

```
<a href="#main" class="skip-link">Skip to main content</a>

<Header />

<main id="main">
  <slot></slot>
</main>
  
<Footer />

<style>
  .skip-link {
    position: absolute;
    opacity: 0;
  }
</style>
```

Dit is hoe het er nu uit ziet met screen reader:

<img width="592" alt="Image" src="https://github.com/user-attachments/assets/8535078b-5235-427d-ad24-b36061d6dd4e" />

Ik heb deze bronnen gebruikt:
- [allyproject: skip link](https://www.a11yproject.com/posts/skip-nav-links/)
- [W3C: bypass blocks](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html)
- [W3C: success criteria](https://www.w3.org/TR/2012/NOTE-WCAG20-TECHS-20120103/G1)

**Comment by lisagjh** [comment]
Merged with PR https://github.com/lisagjh/voorhoede/pull/62

**Comment by lisagjh** [comment]
# Skip Link

I used all sources above to create this skip link. I decided to also have it show when it's in focus. I saw most of the sources do this, so figured it was best practice.

```html
<div id="skip">
  <a href="#content">Skip to main content</a>
</div>

<main id="content">
  <slot></slot>
</main>
```

```css
  #skip a {
    display: block;
    position: absolute;
    left: -999px;
    top: -999px;
    }

#skip a:focus {
    left: 0;
    top: 0;
    padding: .1rem;
    background: var(--white);
    border:1px solid var(--blue);
    }
```
